import assets from "./assets"


const LawyerData = [
    {
        id:"L0001",
        name:"زانیار فەرهاد بهرام",
        experience:"یەک",
        city:"هەولێر",
        level:"راهێنراو",
        degree:"ماستەر",
        ofLocation:"شەقامی گوڵان",
        mobile:7503523626,
        imgProfile:assets.AvatarMan,
        imgSendicate:"",
        cateogory:["قیسام","میرات","کۆمپانیا"],
    },
    {
        id:"L0002",
        name:"محمد فەرهاد بهرام",
        experience:"دوو",
        city:"سلێمانی",
        level:"کارا",
        degree:"بەکالۆریۆس",
        ofLocation:"زیلان ستی",
        mobile:7511042003,
        imgProfile:assets.AvatarMan,
        imgSendicate:"",
        cateogory:["ئابووری","قەتل"],
    },  
    {
        id:"L0003",
        name:"ئازاد خالد محمد",
        experience:"سێ",
        city:"دهۆک",
        level:"راهێنراو",
        degree:"ماستەر",
        ofLocation:"مازی مۆڵ",
        mobile:7509616151,
        imgProfile:assets.AvatarMan,
        imgSendicate:"",
        cateogory:["تلیاک"],
    }, 
    //  {
    //     id:"L0004",
    //     name:"سەمەد محمد احمد",
    //     experience:"پێنچ",
    //     city:"سلێمانی",
    //     level:"کارا",
    //     degree:"بەکالۆریۆس",
    //     ofLocation:"سەهۆڵەکە",
    //     mobile:"٠٧٧٣٤٥٦٧٧٨٨",
    //     imgProfile:assets.AvatarMan,
    //     imgSendicate:"",
    //     cateogory:["قیسام شەرعی","تەڵاق"],
    // },

    // {
    //     id:"L0005",
    //     name:" محمد سەمەد احمد",
    //     experience:"شەش",
    //     city:"هەولێر",
    //     level:"راهێنراو",
    //     degree:"بەکالۆریۆس",
    //     ofLocation:"٨ حەسارۆک",
    //     mobile:"٠٧٨٠٢٦٦٧٧٥٥",
    //     imgProfile:assets.AvatarMan,
    //     imgSendicate:"",
    //     cateogory:["تەڵااق","کۆمپانیا","ارهاب"],
    // },
    // {
    //     id:"L0006",
    //     name:"رەهێل باپیر لاوکۆ ",
    //     experience:"حەوت",
    //     city:"سلێمانی",
    //     level:"کارا",
    //     degree:"بەکالۆریۆس",
    //     ofLocation:"توی مەلیک",
    //     mobile:"٠٧٧٢١١٨٨٢٢٣",
    //     imgProfile:assets.AvatarWoman,
    //     imgSendicate:"",
    //     cateogory:["مادەی بێهۆشکەر","شەر و ئاژاوە"],
    // },
    // {
    //     id:"L0007",
    //     name:"سامان احمد محمد ",
    //     experience:"هەشت",
    //     city:"دهۆک",
    //     level:"راوێژکار",
    //     degree:"دکتۆرا",
    //     ofLocation:"ناو بازار",
    //     mobile:"٠٧٥١٢٢٣٤٤٨٥",
    //     imgProfile:assets.AvatarMan,
    //     imgSendicate:"",
    //     cateogory:[,"تەڵاق"],
    // },
    // {
    //     id:"L0008",
    //     name:"مەمەد عبداللە احمد",
    //     experience:"نۆ",
    //     city:"هەولێر",
    //     level:"ڕاوێژکار",
    //     degree:"ماستەر",
    //     ofLocation:"گەلاوێژ",
    //     mobile:"٠٧٥٠٤٤٥٤٥٤٥",
    //     imgProfile:assets.AvatarMan,
    //     imgSendicate:"",
    //     cateogory:[" تەهدیدکردن"],
    // },
    // {
    //     id:"L0009",
    //     name:"عبداللە کریم ئەلەند",
    //     experience:"دە",
    //     city:"سلێمانی",
    //     level:"راهێنراو",
    //     degree:"بەکالۆریۆس",
    //     ofLocation:"سەرچنار",
    //     mobile:"٠٧٧٢٦٧٨٩٠٩",
    //     imgProfile:assets.AvatarMan,
    //     imgSendicate:"",
    //     cateogory:["کۆپی رایت","دزیکردن","تەشهیرکردن"],
    // },
    // {
    //     id:"L0010",
    //     name:"دیاکۆ  کریم خۆشناو",
    //     experience:"یازدە",
    //     city:"هەولێر",
    //     level:"کارا",
    //     degree:"بەکالۆریۆس",
    //     ofLocation:"ناز  ناز",
    //     mobile:"٠٧٥١٠٠٢٢٧٣",
    //     imgProfile:assets.AvatarMan,
    //     imgSendicate:"",
    //     cateogory:[" خراپ بەکاەهێنانی مۆبایل","دزیکردن","تەشهیرکردن"],
    // },
    // {
    //     id:"L0011",
    //     name:"کرمانج سەرچڵ دهام",
    //     experience:"دوازدە",
    //     city:"سلێمانی",
    //     level:"راوێژکار",
    //     degree:"ماستەر",
    //     ofLocation:"کارێزە وشکە",
    //     mobile:"٠٧٧٠١٢٣٤٥٦٨",
    //     imgProfile:assets.AvatarMan,
    //     imgSendicate:"",
    //     cateogory:[" شەڕ و ئاژاوە","دزیکردن"],
    // },
    // {
    //     id:"L0012",
    //     name:"دارا حاجی حسین",
    //     experience:"سێزدە ",
    //     city:"دهۆک",
    //     level:"راهێنراو",
    //     degree:"بەکالۆریۆس",
    //     ofLocation:"ناو بازار",
    //     mobile:"٠٧٥١٢٣٥٦٧٧٧",
    //     imgProfile:assets.AvatarMan,
    //     imgSendicate:"",
    //     cateogory:["کۆپی رایت"],
    // },
    // {
    //     id:"L0013",
    //     name:"دانا احمد شاهۆ",
    //     experience:"چواردە",
    //     city:"هەولێر",
    //     level:"راوێژکار",
    //     degree:"دکتۆرا",
    //     ofLocation:"بەختیاری",
    //     mobile:"٠٧٥٠٣٣٤٨٨٩٩",
    //     imgProfile:assets.AvatarMan,
    //     imgSendicate:"",
    //     cateogory:["عقارات "],
    // },
    // {
    //     id:"L0014",
    //     name:"کەریم خان برادۆستی ",
    //     experience:"پانزدە",
    //     city:"سلێمانی",
    //     level:"کارا",
    //     degree:"بەکالۆریۆس",
    //     ofLocation:"بەرزاییەکانی سلێمانی",
    //     mobile:"٠٧٧١٦٢٥٨٨٠٠",
    //     imgProfile:assets.AvatarMan,
    //     imgSendicate:"",
    //     cateogory:["دزیکردن","تەزویر"],
    // },
    // {
    //     id:"L0015",
    //     name:" عەلی رەسول حکیم",
    //     experience:"شازدە",
    //     city:"دهۆک",
    //     level:"ڕاوێژکار",
    //     degree:"دکتۆرا",
    //     ofLocation:"فایڤ گەیتس",
    //     mobile:"٠٧٥٠٥٤٥٦٧٨",
    //     imgProfile:assets.AvatarMan,
    //     imgSendicate:"",
    //     cateogory:[" وەکالە","قیسام شيرعی"],
    // },
    // {
    //     id:"L0016",
    //     name:" بابان شامیر ئاغا",
    //     experience:"حەڤدە",
    //     city:"هەولێر",
    //     level:"راهێنراو",
    //     degree:"بەکالۆریۆس",
    //     ofLocation:"ڤیتاڵ",
    //     mobile:"٠٧٥١٩٨٧٥٦٩",
    //     imgProfile:assets.AvatarMan,
    //     imgSendicate:"",
    //     cateogory:["کۆپی رایت"],
    // },
    // {
    //     id:"L0017",
    //     name:"کاکل سەید جبار",
    //     experience:"هەشدە",
    //     city:"دهۆک",
    //     level:"کارا",
    //     degree:"بەکالۆریۆس",
    //     ofLocation:"گەرەکی زانکۆ",
    //     mobile:"٠٧٥٠٩٨٧٦٥٦٧",
    //     imgProfile:assets.AvatarMan,
    //     imgSendicate:"",
    //     cateogory:[" قەتل","ئیقامە","تەشهیرکردن"],
    // },
    // {
    //     id:"L0018",
    //     name:"رێبین هۆشیار بەهادین",
    //     experience:"بیست",
    //     city:"هەولیر",
    //     level:"راهێنراو",
    //     degree:"بەکالۆریۆس",
    //     ofLocation:"ئاری",
    //     mobile:"٠٧٥٠١١١١٦٦٢",
    //     imgProfile:assets.AvatarMan,
    //     imgSendicate:"",
    //     cateogory:["ماف خوراو"],
    // },
    // {
    //     id:"L0019",
    //     name:"عمر کەمال شهرام",
    //     experience:"نۆزدە",
    //     city:"سلێمانی",
    //     level:"راهێنراو",
    //     degree:"بەکالۆریۆس",
    //     ofLocation:"سەرچنار",
    //     mobile:"٠٧٧٢٦٧٨٩٠٩",
    //     imgProfile:assets.AvatarMan,
    //     imgSendicate:"",
    //     cateogory:["کۆپی رایت","دزیکردن","تەشهیرکردن"],
    // },
    // {
    //     id:"L0020",
    //     name:"سۆزان محمد محمود",
    //     experience:"دە",
    //     city:"دهۆک",
    //     level:"راوێژکار",
    //     degree:"ماستەر",
    //     ofLocation:"گەرەکی سەرهەلدان",
    //     mobile:"٠٧٥٠٨٢٦٣٨٣٨٢",
    //     imgProfile:assets.AvatarWoman,
    //     imgSendicate:"",
    //     cateogory:["قەتل","کێشەی کۆمەڵایەتی"],
    // },
    // {
    //     id:"L0021",
    //     name:" مستەفا حاجی خەیروڵا",
    //     experience:"یازدە",
    //     city:"سلێمانی",
    //     level:"راوێژکار",
    //     degree:"دکتۆرا",
    //     ofLocation:"سابونکەران",
    //     mobile:"٠٧٥٠٣٤٥٦٧٨٩",
    //     imgProfile:assets.AvatarMan,
    //     imgSendicate:"",
    //     cateogory:[" توند و تیژی ئافرەت","دزیکردن","تەشهیرکردن"],
    // },
    // {
    //     id:"L0022",
    //     name:"مەهدی کریم سەلام",
    //     experience:"بیست و یەک ",
    //     city:" هەولێر",
    //     level:"راهێنراو",
    //     degree:"بەکالۆریۆس",
    //     ofLocation:"هەولێری نوێ",
    //     mobile:"٠٧٥٠٥٦٦٧٨٦٤",
    //     imgProfile:"",
    //     imgSendicate:assets.AvatarMan,
    //     cateogory:[" دزی کردن","خیانە زەوجی"],
    // },
    // {
    //     id:"L0023",
    //     name:"فەرهەنگ هۆشمەند رەزا",
    //     experience:"سی",
    //     city:"هەولێر",
    //     level:"راوێژکار",
    //     degree:"ماستەر",
    //     ofLocation:"زانیاری",
    //     mobile:"٠٧٥٠٧٣٥٤٤٥",
    //     imgProfile:assets.AvatarMan,
    //     imgSendicate:"",
    //     cateogory:["کۆپی رایت","دزیکردن","تەشهیرکردن"],
    // },
    // {
    //     id:"L0024",
    //     name:"هۆشمەند عەدنان بەدرەدین",
    //     experience:"پێنچ",
    //     city:"سلێمانی",
    //     level:"راهێنراو",
    //     degree:"بەکالۆریۆس",
    //     ofLocation:"با‌غی گشتی",
    //     mobile:"٠٧٧٢٦٧٨٤٠٩",
    //     imgProfile:assets.AvatarMan,
    //     imgSendicate:"",
    //     cateogory:["دزیکردن"],
    // },
    // {
    //     id:"L0025",
    //     name:"یوسف کریم رمزان",
    //     experience:"دوازدە",
    //     city:"دهۆک",
    //     level:"کارا",
    //     degree:"بەکالۆریۆس",
    //     ofLocation:"فەرەنسی تاوەر",
    //     mobile:"٠٧٥٠٩٩٨٨٧٧٦٢",
    //     imgProfile:assets.AvatarMan,
    //     imgSendicate:"",
    //     cateogory:["هەرەشەکردن","اهانەکردن"],
    // },
   
    
 ]
    
        
   
        
   export {LawyerData}